quarkus.datasource.db-kind=${DB_KIND:mysql}
quarkus.datasource.username=${DB_USERNAME:root}
quarkus.datasource.password=${DB_PASSWORD}
quarkus.datasource.jdbc.url=${DB_JDBC_URL:jdbc:mysql://localhost:3306/rutamx}


quarkus.hibernate-orm.database.generation=validate
quarkus.hibernate-orm.log.sql=false
quarkus.hibernate-orm.log.format-sql=false

quarkus.hibernate-orm.schema-management.strategy=${DB_SCHEMA_STRATEGY:update}
firebase.service-account-location=${FIREBASE_SERVICE_ACCOUNT_LOCATION:none}

quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.headers=Content-Type,Authorization
quarkus.http.cors.exposed-headers=Content-Disposition
quarkus.http.cors.methods=GET,POST,PUT,PATCH,DELETE,OPTIONS
quarkus.http.port=8080
firebase.credentials=src/main/resources/rutamx-firebase-adminsdk.json
firebase.project-id=${FIREBASE_PROJECT_ID:rutamx-tec-2604}

# OpenAPI / Swagger UI
quarkus.smallrye-openapi.path=/openapi
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui
mp.openapi.extensions.smallrye.info.title=RutaMx API
mp.openapi.extensions.smallrye.info.version=1.0.0
mp.openapi.extensions.smallrye.info.description=API para simulación y monitoreo de flotilla de autobuses eléctricos en la CDMX

%test.firebase.fail-on-error=false
%test.quarkus.datasource.db-kind=h2
%test.quarkus.datasource.username=sa
%test.quarkus.datasource.password=
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MySQL;DATABASE_TO_LOWER=TRUE
%test.quarkus.datasource.jdbc.driver=org.h2.Driver
%test.quarkus.hibernate-orm.database.generation=drop-and-create
